### ISSUE TITLE
Pupy history disappears 

### ISSUE THREAD

**Issue by CG-root** [alxchk/pupy#14]
Hi,
While I try to open a shell I see that the pupy history being wiped.

How can I cancel this behavior ?

Thanks.

**Comment by alxchk** [comment]
There is no option to disable this, but you can delete from PupyCmd.py lines with SHADOW_SCREEN_TO and SHADOW_SCREEN_FROM

**Comment by alxchk** [comment]
Okay, they are now configurable

```
config set cmdline shadow_screen no
config save
```

**Comment by CG-root** [comment]
thanks !
