### ISSUE TITLE
Impossible to generate a valid .exe. Problem with payloads ?

### ISSUE THREAD

**Issue by quentinhardy** [alxchk/pupy#18]
Hello,

I am using pupy over docker:
```
git clone --recursive https://github.com/alxchk/pupy
./install.sh
./start-compose.sh
```

I'm trying to generate a working .exe but impossible for the moment.

For example, when I try to generate an .exe with one of these following command, the binary crashes:
```
gen -f client --debug
en -f client --debug
gen -f client  connect --host 192.0.1.103:8443
```
I don't know If I'm doing a mistake but it seems binary payloads are invalids.

Where I can find last generated payloads (exe for example)?
Or how I can generate payloads from the docker ?

Thank you in advance

**Comment by alxchk** [comment]
Try:

```
cd client; ./build-docker.sh
```

This (should, if all ok) to compile payloads.
In case you have issues with linux64 - ensure you have enabled vsyscall emulation (usually kernel cmdline argument, depends on distro kernel)

**Comment by quentinhardy** [comment]
Thank you for the help.

I have started the command _./build-docker.sh_.

However, I have the following error in the docker _build-pupy-windows_:
```
[+] Build sources with toolchain alxchk/tc-windows
[+] Install python packages
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x012269D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',)': /simple/pip/
[...]
```
It seems there is not Internet access from this docker.
I have not found a fix yet -:(,

**Comment by alxchk** [comment]
Yes, looks like connectivity issue. Do you have proxy, or something like that? You probably should check your docker setup

**Comment by quentinhardy** [comment]
It works now for a win32 exe.
Luckily you are here for this awesome project.

Big thank you to maintain this project. Very useful.
