### ISSUE TITLE
Bug in rdesktop module

### ISSUE THREAD

**Issue by quentinhardy** [alxchk/pupy#19]
Hello,

It seems there is a bug in _rdesktop_ module.

When you try to connect to given url (e.g. _http://127.0.0.1:9000/Y2Di4MxAuq_), there is the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2195, in finish
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2215, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 194, in __init__
    self.initialize(**kwargs)
  File "/opt/pupy/modules/rdesktop.py", line 126, in initialize
    super(IndexHandler, self).initialize(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2020-01-10 15:33:05,881| Uncaught exception
```

Moreover, I have notice the _local_ips_ parameter is missing from the _pupy.conf_ file.
It should be great if it is fixed to "_local_ips = 127.0.0.1_" by default for example.
Indeed, the user has to modify this parameter to his host IP address if he uses _./start-compose.sh_ - docker.

Thank you,

**Comment by alxchk** [comment]
Something strange here. There is a bug with local_ips, because PupyWeb always used built-in LOCAL_IPS (this one I pushed). The one with type error - very strange. Can you check tornado version?

**Comment by quentinhardy** [comment]
It works if I modify _LOCAL_IPS_ in _PupyWeb.py_ and I add my host IP address. Thank you.

If you want, I can create a pull request to append an option in _rdesktop.py_ for allowing a specific IP address? Do you have an email address if I have some questions ?

**Comment by alxchk** [comment]
> It works if I modify LOCAL_IPS in PupyWeb.py and I add my host IP address

The one with LOCAL_IPS I pushed in https://github.com/alxchk/pupy/commit/9f2ae9bd3a8721b1d29711edbb9029ed22f23f1d so in theory
config set webserver local_ips AAA.BBB.CCC.DDD should have same effect.

> Do you have an email address if I have some questions ?

You can use my nick + @gmail.com )

**Comment by quentinhardy** [comment]
Thanks, it works with "config set webserver local_ips X.Y.Z.A"
