### ISSUE TITLE
Update poster library to corresponding python3 library

### ISSUE THREAD

**Issue by jayrod** [alxchk/pupy#27]
**ISSUE TYPE**
Bug

**SUMMARY**

poster library is python 2 only and should be changed to "poster3" library from pypi

**STEPS TO REPRODUCE**
[asciienma](https://asciinema.org/a/327138)

**EXPECTED OUTCOME**
All Requirements are installed

**PYTHON VERSION**
Python 3.8.2

**SUPPORTED OS**
Kali GNU/Linux Rolling

**Comment by alxchk** [comment]
This is already done in futurize branch
