### ISSUE TITLE
Please change the variable to clients

### ISSUE THREAD

**Issue by CG-root** [alxchk/pupy#6]
https://github.com/alxchk/pupy/blob/db13904ec4366590aa1b77677f9110c211516d06/pupy/commands/sessions.py#L55

**Comment by CG-root** [comment]
@alxchk . thanks for the quick commit.
btw, how can I update Pupy after it was deployed already?

**Comment by alxchk** [comment]
You mean docker? In case you properly mounted projects folder, you can just do docker pull for the newest image

**Comment by CG-root** [comment]
I used the instructions from the wiki and want to know how each time I can perform an update for the pupy source code

**Comment by alxchk** [comment]
In that case you should have **pupysh-update** script at **pupyws/bin** folder
