### ISSUE TITLE
No handlers could be found for logger "pupy.network.pss"

### ISSUE THREAD

**Issue by justinemar** [alxchk/pupy#8]
Installation went smoothly but when i try to run any commands i get the following error without any further details
> No handlers could be found for logger "pupy.network.pss"

**Comment by alxchk** [comment]
Can you try to do the same with a bit older head (https://github.com/n1nj4sec/pupy)?
Also please do the screenshot or better record asciinema (https://asciinema.org/).
You can also enable debug (--log-level DEBUG)

**Comment by alxchk** [comment]
This exact message should be fixed with https://github.com/alxchk/pupy/commit/67596fb77edaaf078098648eb91e4633e55f57ed
